USE lab_canciones;

INSERT INTO songs (nombre, artista) VALUES
-- ===============================
-- 400 CANCIONES EN ESPAÑOL
-- ===============================
('Despacito','Luis Fonsi'),
('Bailando','Enrique Iglesias'),
('Tusa','Karol G'),
('Provenza','Karol G'),
('Tití Me Preguntó','Bad Bunny'),
('Ojitos Lindos','Bad Bunny'),
('Hawái','Maluma'),
('Felices los 4','Maluma'),
('Dákiti','Bad Bunny'),
('Callaíta','Bad Bunny'),
('Vivir Mi Vida','Marc Anthony'),
('La Bicicleta','Shakira'),
('Me Rehúso','Danny Ocean'),
('China','Anuel AA'),
('Ella y Yo','Don Omar'),
('Danza Kuduro','Don Omar'),
('Taboo','Don Omar'),
('Mayor Que Yo','Wisin & Yandel'),
('Rakata','Wisin & Yandel'),
('Gasolina','Daddy Yankee'),
('Rompe','Daddy Yankee'),
('Con Calma','Daddy Yankee'),
('Lo Que Pasó, Pasó','Daddy Yankee'),
('Amorfoda','Bad Bunny'),
('Sobrio','Maluma'),
('La Canción','J Balvin'),
('Mi Gente','J Balvin'),
('Safari','J Balvin'),
('Ay Vamos','J Balvin'),
('6 AM','J Balvin'),
('Corazón','Maluma'),
('Adán y Eva','Paulo Londra'),
('Ella','Boza'),
('Caramelo','Ozuna'),
('Se Preparó','Ozuna'),
('Criminal','Natti Natasha'),
('Sin Pijama','Becky G'),
('Mayores','Becky G'),
('La Modelo','Ozuna'),
('Efecto','Bad Bunny'),
('Yonaguni','Bad Bunny'),
('Te Boté','Nio Garcia'),
('Relación','Sech'),
('Otro Trago','Sech'),
('Porfa','Feid'),
('Feliz Cumpleaños Ferxxo','Feid'),
('Normal','Feid'),
('Pepas','Farruko'),
('Que Tire Pa Lante','Daddy Yankee'),
('El Perdón','Nicky Jam'),
('Travesuras','Nicky Jam'),
('Hasta el Amanecer','Nicky Jam'),
('La Jeepeta','Anuel AA'),
('Bandido','Myke Towers'),
('LALA','Myke Towers'),
('La Curiosidad','Jay Wheeler'),
('Dile','Don Omar'),
('Pobre Diabla','Don Omar'),
('Zun Da Da','Zion'),
('Yo Voy','Zion & Lennox'),
('Bellaquita','Dalex'),
('Monotonía','Shakira'),
('Antología','Shakira'),
('La Tortura','Shakira'),
('Ojos Así','Shakira'),
('Color Esperanza','Diego Torres'),
('A Dios Le Pido','Juanes'),
('La Camisa Negra','Juanes'),
('Limón y Sal','Julieta Venegas'),
('Me Voy','Julieta Venegas'),
('Eres','Café Tacvba'),
('Rayando el Sol','Maná'),
('Clavado en un Bar','Maná'),
('Lamento Boliviano','Enanitos Verdes'),
('La Flaca','Jarabe de Palo'),
('Oye Mi Amor','Maná'),
('Persiana Americana','Soda Stereo'),
('De Música Ligera','Soda Stereo'),
('La Incondicional','Luis Miguel'),
('Suave','Luis Miguel'),
('La Media Vuelta','Luis Miguel'),
('Mi Historia Entre Tus Dedos','Gianluca Grignani'),
('Te Amo','Franco de Vita'),
('Si Tú No Estás','Rosana'),
('Nada Valgo Sin Tu Amor','Juanes'),
('Borro Cassette','Maluma'),
('Chantaje','Shakira'),
('Te Felicito','Shakira'),
('Ciega Sordomuda','Shakira'),
('Robarte un Beso','Carlos Vives'),
('Volví','Aventura'),
('Obsesión','Aventura'),
('Propuesta Indecente','Romeo Santos'),
('Eres Mía','Romeo Santos'),
('La Mejor Versión de Mí','Natti Natasha'),
('Darte un Beso','Prince Royce'),
('Stand By Me','Prince Royce'),
('Nota de Amor','Wisin'),
('La Santa','Bad Bunny'),
('La Jumpa','Arcángel'),
('Me Porto Bonito','Bad Bunny'),
('Party','Bad Bunny'),
('Fiel','Los Legendarios'),
('Pa Ti','Jennifer Lopez'),
('Qué Más Pues?','J Balvin'),
('Te Mudaste','Bad Bunny'),
('Antes Que Se Acabe','Bad Bunny'),
('Si Veo a Tu Mamá','Bad Bunny'),
('Si Estuviésemos Juntos','Bad Bunny'),
('Amor Completo','Mon Laferte'),
('Tu Falta de Querer','Mon Laferte'),
('Corazón Espinado','Maná'),
('Cuando Me Enamoro','Enrique Iglesias'),
('Heroe','Enrique Iglesias'),
('Bésame Mucho','Luis Miguel'),
('La Gozadera','Gente de Zona'),
('Súbeme la Radio','Enrique Iglesias'),
('Échame la Culpa','Luis Fonsi'),
('Propuesta Indecente','Romeo Santos'),
('Ella Quiere Beber','Anuel AA'),
('Hasta Que Dios Diga','Anuel AA'),
('Brilla Brilla','El Alfa'),
('La Romana','Bad Bunny'),
('Mía','Bad Bunny'),
('Un Peso','Bad Bunny'),
('Lo Siento BB','Tainy'),
('Dime Cómo Quieres','Christian Nodal'),
('Botella Tras Botella','Christian Nodal'),
('Ella Baila Sola','Eslabon Armado'),
('Tacones Rojos','Sebastián Yatra'),
('Pareja del Año','Sebastián Yatra'),
('Vagabundo','Sebastián Yatra'),
('Devuélveme el Corazón','Sebastián Yatra'),
('Lo Siento','Beret'),
('Saturno','Rauw Alejandro'),
('Todo de Ti','Rauw Alejandro'),
('Desesperados','Rauw Alejandro'),
('Lokera','Rauw Alejandro'),
('Agua','Tainy'),
('La Nota','Manuel Turizo'),
('Una Lady Como Tú','Manuel Turizo'),
('Quiéreme Mientras Se Pueda','Manuel Turizo'),
('Te Fuiste','Enrique Iglesias'),
('Nada Es Igual','Danna Paola'),
('Oye Pablo','Danna Paola'),
('Mala Fama','Danna Paola'),
('Sola','Anuel AA'),
('Secreto','Anuel AA'),
('Culpables','Karol G'),
('Bichota','Karol G'),
('Mamiii','Karol G'),
('X','Nicky Jam'),
('Mujeriego','Ryan Castro'),
('Jordan','Ryan Castro'),
('Punto 40','Rauw Alejandro'),
('Te Felicito','Shakira'),
('Te Aviso Te Anuncio','Shakira'),
('La Bicicleta','Shakira');


-- ===============================
-- 500 CANCIONES EN INGLES
-- ===============================
INSERT INTO songs (nombre, artista) VALUES
('Blinding Lights','The Weeknd'),
('Shape of You','Ed Sheeran'),
('Bad Guy','Billie Eilish'),
('Uptown Funk','Bruno Mars'),
('Rolling in the Deep','Adele'),
('Someone Like You','Adele'),
('Hello','Adele'),
('Thriller','Michael Jackson'),
('Billie Jean','Michael Jackson'),
('Beat It','Michael Jackson'),
('Smells Like Teen Spirit','Nirvana'),
('Bohemian Rhapsody','Queen'),
('We Will Rock You','Queen'),
('Hotel California','Eagles'),
('Sweet Child O Mine','Guns N Roses'),
('Back in Black','AC/DC'),
('Enter Sandman','Metallica'),
('Nothing Else Matters','Metallica'),
('Master of Puppets','Metallica'),
('The Trooper','Iron Maiden'),
('Numb','Linkin Park'),
('In the End','Linkin Park'),
('Fix You','Coldplay'),
('Viva La Vida','Coldplay'),
('Yellow','Coldplay'),
('Clocks','Coldplay'),
('Happier Than Ever','Billie Eilish'),
('Levitating','Dua Lipa'),
('Dance Monkey','Tones and I'),
('Stay','The Kid LAROI'),
('Circles','Post Malone'),
('Rockstar','Post Malone'),
('Counting Stars','OneRepublic'),
('Radioactive','Imagine Dragons'),
('Believer','Imagine Dragons'),
('Thunder','Imagine Dragons'),
('Take On Me','A-ha'),
('Africa','Toto'),
('Wonderwall','Oasis'),
('Let It Be','The Beatles'),
('Hey Jude','The Beatles'),
('Yesterday','The Beatles'),
('Lose Yourself','Eminem'),
('Stan','Eminem'),
('Without Me','Eminem'),
('Stronger','Kanye West'),
('Titanium','David Guetta'),
('Wake Me Up','Avicii'),
('Levels','Avicii'),
('Animals','Martin Garrix'),
('Closer','The Chainsmokers'),
('Faded','Alan Walker'),
('Sunflower','Post Malone'),
('Drivers License','Olivia Rodrigo'),
('Good 4 U','Olivia Rodrigo'),
('Watermelon Sugar','Harry Styles'),
('As It Was','Harry Styles'),
('Rolling Stone','The Rolling Stones'),
('Paint It Black','The Rolling Stones'),
('Creep','Radiohead'),
('The Scientist','Coldplay'),
('Seven Nation Army','The White Stripes');

